# Pandas Basics

### Object in Python
Class -> Object/instance    
Variables/attribute
Functions/Methods

Pandas has two data types
1. Series - 1D array/list
2. Dataframe - 2 or nore dimension array

In [1]:
import pandas as pd
import numpy as np

In [2]:
l1  = [2,3,46,6,8,9]

In [3]:
l1[2]

46

In [4]:
sdata1 = [2,4,7,8,3,6]

### Pandas Series
- Syntax   
Pandasobj1 = pd.Series(data,index)

In [5]:
pseries1 = pd.Series(sdata1)

In [6]:
pseries1

0    2
1    4
2    7
3    8
4    3
5    6
dtype: int64

In [7]:
pseries1[2]

7

In [8]:
sdata2 = [2,7,9,4,7]

In [9]:
pseries2 = pd.Series(sdata2)

In [10]:
pseries2

0    2
1    7
2    9
3    4
4    7
dtype: int64

In [11]:
pseries2[2]

9

In [12]:
pseries2[1]

7

In [13]:
pseries2[4]

7

In [14]:
sdata3 = [34,55,67,88,33]
indexdata3 = ['jan','feb','march','april','may']
pseries3 = pd.Series(sdata3,indexdata3)

In [15]:
pseries3

jan      34
feb      55
march    67
april    88
may      33
dtype: int64

In [16]:
pseries3['march']

67

In [17]:
var1 = np.arange(2,12,3)
print(var1)

[ 2  5  8 11]


In [18]:
type(var1)

numpy.ndarray

In [19]:
type(l1)

list

In [20]:
sdata4 = np.arange(2,15,3)
sdata4

array([ 2,  5,  8, 11, 14])

In [21]:

indexdata4 = ['a','b','c','d','e']
pseries4 =pd.Series(sdata4,indexdata4)


In [22]:
pseries4

a     2
b     5
c     8
d    11
e    14
dtype: int64

In [23]:
sdata5 = [2,5,6,np.NAN,3,np.NaN,7]
pseries5 = pd.Series(sdata5)

In [24]:
pseries5

0    2.0
1    5.0
2    6.0
3    NaN
4    3.0
5    NaN
6    7.0
dtype: float64

In [25]:
pseries5[5]

nan

In [26]:
dir(pseries1)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__rep

In [29]:
pseries1.index

RangeIndex(start=0, stop=6, step=1)

In [30]:
pseries1

0    2
1    4
2    7
3    8
4    3
5    6
dtype: int64

In [32]:
pseries3.index

Index(['jan', 'feb', 'march', 'april', 'may'], dtype='object')

In [33]:
pseries3.values

array([34, 55, 67, 88, 33])

In [34]:
pseries3

jan      34
feb      55
march    67
april    88
may      33
dtype: int64

In [35]:
pseries3.dtype

dtype('int64')

In [36]:
pseries3.shape

(5,)

In [37]:
pseries3.nbytes

40

In [38]:
pseries3.ndim

1

In [39]:
pseries3.size

5

In [44]:
pseries5.hasnans

True

In [45]:
pseries5

0    2.0
1    5.0
2    6.0
3    NaN
4    3.0
5    NaN
6    7.0
dtype: float64

### Accessing Series elements

In [46]:
pseries3['jan']

34

In [49]:
pseries1[1:4]

1    4
2    7
3    8
dtype: int64

In [48]:
pseries1

0    2
1    4
2    7
3    8
4    3
5    6
dtype: int64

In [ ]:
pseries1[:4] # stop value

0    2
1    4
2    7
3    8
dtype: int64

In [52]:
pseries1[2:] #start index value

2    7
3    8
4    3
5    6
dtype: int64

### Operations in Series

In [53]:
pseries3

jan      34
feb      55
march    67
april    88
may      33
dtype: int64

In [ ]:
pseries3['jan'] =45  #Updating vale of series element

In [56]:
pseries2

0    2
1    7
2    9
3    4
4    7
dtype: int64

In [55]:
pseries3

jan      45
feb      55
march    67
april    88
may      33
dtype: int64

In [ ]:
pseries2.index = ['a','b','c','d','e'] #Changing index

In [58]:
pseries2

a    2
b    7
c    9
d    4
e    7
dtype: int64